// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd0NfPtXtUcatcaKhFHYrC5Pch02SxaOY',
    appId: '1:363173741787:android:c2e44609e04f2fe73d38fe',
    messagingSenderId: '363173741787',
    projectId: 'ebookdemo-1',
    storageBucket: 'ebookdemo-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWI99oLf-SMCSuwVRcmoSIq_A_BSo4w4g',
    appId: '1:363173741787:ios:d0db0484ad914c663d38fe',
    messagingSenderId: '363173741787',
    projectId: 'ebookdemo-1',
    storageBucket: 'ebookdemo-1.firebasestorage.app',
    androidClientId: '363173741787-nusb3bndgqh70m9dr54b8ik7pu1501j3.apps.googleusercontent.com',
    iosClientId: '363173741787-rk55qbjhsici1apb8q484jfdbm63j7f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBookReader',
  );

}